baseURL = "https://garrypolley.com/"
languageCode = "en-us"
title = "Garry Polley"
theme = "anatole"
enableEmoji = true
pygmentsCodeFences = true   # Enable triple backtick 'code fence' markdown
pygmentsUseClasses = false  # Add inline styles, no need to compile extra CSS

[permalinks]
  post = "/:year/:month/:day/:slug/"
  recipe = "/recipe/:slug/"

[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "post"
url = "/post/"

[[menu.main]]
name = "Recipes"
weight = 300
identifier = "recipe"
url = "/recipe/"

[[menu.main]]
name = "Contact"
weight = 400
identifier = "contact"
url = "/contact/"

[params]
title = "🌭Garry Polley"
author = "Garry Polley"
description = "I make computers go"
profilePicture = "images/garry-and-child.JPG"
customCss = ["css/recipe.css"]
mainSections = ["post", "recipe"]


[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/garrypolley/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/garrypolley/"

[[params.socialIcons]]
icon = "fa-file"
title = "Resume"
url = "https://docs.google.com/document/d/1NT3KopYqebcJH9rV3D-gT1ie2CNhnbR8u01BIJDaWOU/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "Email"
url = "mailto:garrympolley@gmail.com"