[build]
publish = "public"
command = "hugo --gc --minify"
base_dir = ""

[[redirects]]
  from = "https://recipe.garrypolley.com/"
  to = "https://recipe.garrypolley.com/recipe/"
  status = 200

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"
