[build]
publish = "public"
command = "hugo --gc --minify"
base = ""

[[redirects]]
  from = "https://blog.garrypolley.com/"
  to = "https://garrypolley.com/post/"
  status = 301
  force = true

[[redirects]]
  from = "https://recipe.garrypolley.com/"
  to = "https://garrypolley.com/recipe/"
  status = 301
  force = true

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"
